platform :ios, '8.0'
use_frameworks!
target 'YunDianEmail' do
     pod 'AFNetworking', '~> 3.0'
     pod 'MJRefresh'
     pod 'MJExtension'
     pod 'Masonry'
     pod 'MBProgressHUD', '~> 1.0.0'
     pod 'AttributedTextView'
     pod 'FMDB'
end
